# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/95281c7a-4de9-463c-ac20-85c71992f42a";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:3" "discard=async" "commit=120" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/95281c7a-4de9-463c-ac20-85c71992f42a";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:3" "discard=async" "commit=120" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/95281c7a-4de9-463c-ac20-85c71992f42a";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:3" "discard=async" "commit=120" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/95281c7a-4de9-463c-ac20-85c71992f42a";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "discard=async" "commit=120" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B04-06DA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a21875d7-e2b9-4128-9ec7-229bfed82408"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
